name: Promote DEV to UAT

on:
  push:
    branches:
      - DEV

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR DEV â†’ UAT
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "DEV"
          destination_branch: "UAT"
          github_token: ${{ secrets.GITHUB_TOKEN }}
            